

-- TABELA USUARIO --
CREATE TABLE USUARIO (	COD_USUARIO	VARCHAR(20) NOT NULL,
						ICONE		VARBINARY(MAX) )

ALTER TABLE USUARIO ADD PRIMARY KEY (COD_USUARIO)

-- TABELA DE COMPROMISSOS DO USUARIO --
CREATE TABLE COMPROMISSO(	SEQ_COMPROMISSO INT NOT NULL IDENTITY(1,1),
							COD_USUARIO		VARCHAR(20),
							DESCRICAO		VARCHAR(100),
							DT				DATETIME,
							HORA			VARCHAR(5),
							IND_CONCLUIDO	CHAR(1),
							QTD_PARTIC		INT
							)


ALTER TABLE COMPROMISSO ADD PRIMARY KEY (SEQ_COMPROMISSO)


-- TABELA DE USUARIOS CONVIDADOS PARA OS COMPROMISSOS --
CREATE TABLE COMPROMISSO_CONVITE(	SEQ_CONVITE		INT NOT NULL IDENTITY(1,1),
									SEQ_COMPROMISSO	INT NOT NULL,
									COD_USUARIO		VARCHAR(20) NOT NULL,
									IND_ACEITO		CHAR(1),
									DT				DATETIME
								)

ALTER TABLE COMPROMISSO_CONVITE ADD PRIMARY KEY (SEQ_CONVITE)


-- TABELA DE NOTIFICACOES --
CREATE TABLE NOTIFICACAO(	SEQ_NOTIFICACAO	INT NOT NULL IDENTITY(1,1),
							COD_USUARIO_DE VARCHAR(20) NOT NULL,
							COD_USUARIO_PARA VARCHAR(20) NOT NULL,							
							DT				DATETIME,
							TEXTO			VARCHAR(500),
							TIPO			CHAR(1), -- "T" ou "C"
							SEQ_COMPROMISSO	INT,
							IND_LIDO		CHAR(1)
						)

ALTER TABLE NOTIFICACAO ADD PRIMARY KEY (SEQ_NOTIFICACAO)


